apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-nfs-pvc-0
  namespace: default
spec:
  storageClassName: nfs-storage-pool0
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: nginx-nfs-site
  namespace: default
  name: nginx-nfs-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-nfs-site
  template:
    metadata:
      labels:
        app: nginx-nfs-site
    spec:
      volumes:
        - name: nginx-nfs-volume
          persistentVolumeClaim:
            claimName: nginx-nfs-pvc-0
      containers:
        - image: nginx
          name: nginx-nfs-site
          command: [ 'sh', '-c', 'echo "<h1>The remote NFS volume is mounted!</h1>" > /usr/share/nginx/html/index.html && nginx && sleep 3600' ]
          resources:
            limits:
              memory: 100Mi
          volumeMounts:
            - name: nginx-nfs-volume
              mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nfs-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-nfs-site
  type: LoadBalancer
