CREATE TABLE IF NOT EXISTS `domains` (
  `uuid` varchar(48) NOT NULL,
  `memory` int(11) DEFAULT NULL,
  `vcpu` int(11) DEFAULT NULL,
  `image` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `cdrom` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `boot` varchar(48) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `networkuuid1` varchar(48) DEFAULT NULL,
  `nicmodel1` varchar(48) DEFAULT NULL,
  `diskbus` varchar(48) DEFAULT NULL,
  `status` varchar(48) DEFAULT NULL,
  `statustime` varchar(48) DEFAULT NULL,
  `action` varchar(48) DEFAULT NULL,
  `timestamp` varchar(48) DEFAULT NULL,
  `mac` varchar(17) DEFAULT NULL,
  `locktonode` varchar(5) DEFAULT NULL,
  `port` int(11) DEFAULT NULL,
  `display` varchar(12) DEFAULT NULL,
  `networkid1` int(11) DEFAULT NULL,
  `imagename` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `networkname1` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `name` varchar(256) DEFAULT NULL,
  `user` varchar(256) DEFAULT NULL,
  `macname` varchar(256) DEFAULT NULL,
  `nicmac1` varchar(17) DEFAULT NULL,
  `imagetype` varchar(5) DEFAULT NULL,
  `image2` varchar(256) DEFAULT NULL,
  `image2name` varchar(256) DEFAULT NULL,
  `image2type` varchar(5) DEFAULT NULL,
  `image3` varchar(256) DEFAULT NULL,
  `image3name` varchar(256) DEFAULT NULL,
  `image3type` varchar(5) DEFAULT NULL,
  `image4` varchar(256) DEFAULT NULL,
  `image4name` varchar(256) DEFAULT NULL,
  `image4type` varchar(5) DEFAULT NULL,
  `notes` text,
  `macip` varchar(15) DEFAULT NULL,
  `maccpucores` int(4) DEFAULT NULL,
  `networkuuid2` varchar(48) DEFAULT NULL,
  `networkid2` varchar(48) DEFAULT NULL,
  `networkname2` varchar(256) DEFAULT NULL,
  `nicmac2` varchar(17) DEFAULT NULL,
  `networkuuid3` varchar(48) DEFAULT NULL,
  `networkid3` varchar(48) DEFAULT NULL,
  `networkname3` varchar(256) DEFAULT NULL,
  `nicmac3` varchar(17) DEFAULT NULL,
  `autostart` varchar(16) DEFAULT NULL,
  `system` varchar(256) DEFAULT NULL,
  `os` varchar(256) DEFAULT NULL,
  `hostname` varchar(256) DEFAULT NULL,
  `created` varchar(48) DEFAULT NULL,
  `opemail` varchar(256) DEFAULT NULL,
  `opfullname` varchar(256) DEFAULT NULL,
  `opphone` varchar(256) DEFAULT NULL,
  `email` varchar(256) DEFAULT NULL,
  `fullname` varchar(256) DEFAULT NULL,
  `phone` varchar(256) DEFAULT NULL,
  `services` varchar(256) DEFAULT NULL,
  `recovery` text,
  `alertemail` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE KEY `domains-index` (`uuid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
